### ISSUE TITLE
Material Designs Link is a 404

### ISSUE THREAD

**Issue by russoj88** [wrnrlr/awesome-gio#7]
The link to "Material design icons" under [Community Libraries](https://github.com/wrnrlr/awesome-gio#community-libraries) is dead.

**Comment by wrnrlr** [comment]
That is possible but I don't update this repo anymore since I stopped using Gio

**Comment by russoj88** [comment]
@wrnrlr since you stopped using Gio, could you transfer ownership of the repo to me?  If not, would you be willing to add a link to a new "awesome-go" repo?

https://gophers.slack.com/archives/CM87SNCGM/p1643999930478589

**Comment by wrnrlr** [comment]
Sure, feel free to fork it and send me a link

**Comment by russoj88** [comment]
https://github.com/russoj88/awesome-gio

Thank you!
